//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusikrApi.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandaUsuario
    {
        public int BandaUsuarioId { get; set; }
        public Nullable<int> BandaFK { get; set; }
        public Nullable<int> UsuarioFK { get; set; }
        public bool isAdmin { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
