//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusikrApi.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneroMusical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneroMusical()
        {
            this.BandaGeneroMusical = new HashSet<BandaGeneroMusical>();
            this.UsuarioGeneroMusical = new HashSet<UsuarioGeneroMusical>();
        }
    
        public int GeneroMusicalId { get; set; }
        public string Nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BandaGeneroMusical> BandaGeneroMusical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioGeneroMusical> UsuarioGeneroMusical { get; set; }
    }
}
