//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusikrApi.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioInstrumento
    {
        public int UsuarioInstrumentoId { get; set; }
        public int UsuarioFk { get; set; }
        public int InstrumentoFk { get; set; }
    
        public virtual Instrumento Instrumento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
