//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusikrApi.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaga()
        {
            this.VagaCandidato = new HashSet<VagaCandidato>();
        }
    
        public int VagaId { get; set; }
        public int BandaFK { get; set; }
        public bool Ativo { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> InstrumentoFK { get; set; }
        public System.DateTime CriadoEm { get; set; }
        public int UsuarioFK { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Instrumento Instrumento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VagaCandidato> VagaCandidato { get; set; }
    }
}
