//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusikrApi.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VagaCandidato
    {
        public int VagaCandidatoId { get; set; }
        public int VagaFK { get; set; }
        public int UsuarioFK { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vaga Vaga { get; set; }
    }
}
